version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    # login to ECR
    - eval $(aws ecr get-login-password --region us-east-1 | sed 's|https://||')
    - REPO_URI=060894855401.dkr.ecr.us-east-1.amazonaws.com/sandyman/laravel-docker-aws
    - IMAGE_TAG=1.1
  build:
    commands:
    - echo Build started on `date`
    - echo installer composer...
    - composer install
    - echo creating .env file
    - cp .env.example .env
    - echo generating app key
    - php artisan key:generate
    - echo build the Docker image...
    - docker build --tag "$REPO_URI:latest" .
    - docker tag "$REPO_URI:latest" "$REPO_URI:$IMAGE_TAG"
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image
    - docker image ls -a 
    - docker push "$REPO_URI:$IMAGE_TAG"
